-intstyle "ise" -incremental -lib "secureip" -o "C:/Users/NN/Desktop/LPRS2/lab2/synthesis/lab2/top_tb_isim_beh.exe" -prj "C:/Users/NN/Desktop/LPRS2/lab2/synthesis/lab2/top_tb_beh.prj" "work.top_tb" 
